### PR TITLE
Add Blue Bottle Coffee

### PR DESCRIPTION
**Pull request by rochers**
Blue Bottle has several remote software engineers including @pwnela (Atlanta) @caseygipson (Denver) @dlachasse (Portland).

### CODE REVIEW

**Comment by jessicard** [comment]
Thanks, this is great @rochers! For the company profile, do you mind filling one out and adding it to https://github.com/jessicard/remote-jobs/tree/master/company-profiles and linking to it in the table? You'll be the first! :)

**Comment by rochers** [comment]
@jessicard Ahhhh I :eyes: -- yep, doing it now.

**Comment by jessicard** [comment]
Thanks taking the time to do that, very appreciated!

**Comment by rochers** [comment]
@jessicard :bow: added

**Comment by jessicard** [comment]
@rochers This is perfect. Thanks for setting a great standard!

**Pull request merged**
