### PR TITLE
ThreatSim is now Wombat Security

### PR DESCRIPTION
**Pull request by veverkap**

### CODE REVIEW

**Comment by dougaitken** [comment]
Hey @veverkap, are you able to create a company profile? 

I also noticed an error in the alphabeticalising of the list, when you resubmit, can you move Wolfram below Wildbit please, I'll fix in main.

**Comment by veverkap** [comment]
@dougaitken I'll make a company profile in a separate PR

**Comment by dougaitken** [comment]
Cheers @veverkap :+1:

**Comment by dougaitken** [comment]
Make sure you pull in any changes before submitting the company profile, thanks @veverkap

**Pull request merged**
