### PR TITLE
Added General Assembly

### PR DESCRIPTION
**Pull request by joshpuetz**

### CODE REVIEW

**Comment by jessicard** [comment]
Thank you! :ice_cream:

**Comment by jessicard** [comment]
I took a look and didn't immediately notice it being remote-friendly - is that stated somewhere by chance, @joshpuetz ?

**Comment by joshpuetz** [comment]
It's not stated now that I look, but I work on the engineering team, and over half of our 30 engineers are remote!

**Comment by jessicard** [comment]
Oh nice, might be nice to add on your website so people know! Thanks for the feedback :)

**Comment by joshpuetz** [comment]
Likewise, thank you!

**Pull request merged**
