### PR TITLE
Remove profile column, link company name to profile instead

### PR DESCRIPTION
**Pull request by hkdobrev**
See a preview here: https://github.com/hkdobrev/remote-jobs/tree/link-company-name-to-profile

### CODE REVIEW

**Comment by jessicard** [comment]
This is a great idea! https://github.com/jessicard/remote-jobs/commit/4136b89681d2011ca7bd6c43ef8234b3697e86fe removed number of brands from the README - do you mind updating your PR so I can merge it?

**Comment by hkdobrev** [comment]
@jessicard Updated.

**Comment by jessicard** [comment]
Thanks @hkdobrev!

**Comment by hkdobrev** [comment]
@jessicard Thank you!

**Comment by hkdobrev** [comment]
I just wanted to say I am sorry to all the contributors for all the conflicts I've created with #56 and #61, but I hope this way it's better for future contributions.

**Comment by jessicard** [comment]
I agree it's a better way forward. I'll help them resolve their conflicts hopefully :) Thank you for your help!

**Pull request merged**
