### PR TITLE
amend skillshare and 112 links

### PR DESCRIPTION
**Pull request by dougaitken**
URL changes. 

I'm not 100% about Skillshare, I think the job posting on WeWorkRemotely, as pulled in through @whatasunnyday's script in #40 is actually about teaching jobs rather than working for Skillshare in the team.

### CODE REVIEW

**Comment by jessicard** [comment]
Thank you! I wonder if we should remove skillshare? I'll merge your PR as is for now.

**Comment by dougaitken** [comment]
I guess it depends what we're looking to share here, is it jobs with companies, or jobs in general through companies who offer them? Like Crew that I added, they have vacancies within the Crew team, but also for those who want to use Crew to get work. 

Worth a thought for more discussion as this grows

**Comment by whatasunnyday** [comment]
Just as a heads up, I think Upwork Pro is similar. 

I think it makes sense to remove these jobs since you're not directly employed by them. The companies actually offering remote jobs should be added to the list.

**Comment by dougaitken** [comment]
I'm going to be working my way through the missing company profiles so I'll defo look to cutting out listings which aren't directly to be employed by the company

**Pull request merged**
