### PR TITLE
Added Hyperion Development South Africa

### PR DESCRIPTION
**Pull request by LadySith**
This is a modified version of the [Contributing Guidelines](/CONTRIBUTING.md).

This pull request adheres to the repository's [Code of Conduct](/CODE_OF_CONDUCT.md)
- [x] This PR contains housekeeping (URL edits, copy changes etc)
- [x] You know your alphabet - company is listed in alphabetical order in the README
- [x] A company profile is included - Not essential but it really helps!
- [x] The company directly hires employees - This may sounds odd but while awesome, this list is not for coding bootcamps, "teaching" positions a network (Teacher positions employed directly, such as Treehouse, are allowed), or networking sites for listing a CV looking for gigs
- [x] The company added hires remote employees, or positions are available to remote workers and are clearly illustrated as such
- [x] A company-profile has been included for each addition to the list
- [ ] I am an employee of the company mentioned and confirm all details are correct
- [x] **Remote status** has details regarding how the culture includes remote employees, how the company integrated remote workers, etc
- [x] **Region** details any restrictions to applicants based on geography
- [x] **How to apply** details the best approach for new applications, link to open positions, and any other help available for job hunters
- [ ] Any missing parts from the profile, please use <Unknown> to allow for future completion

### CODE REVIEW

**Comment by dougaitken** [comment]
Hi @LadySith, this is great if this is related to positions listed on this page https://hyperiondev.com/jobs, do you want to edit the PR to include this?

**Comment by LadySith** [comment]
Hi @dougaitken. Yes the PR should include that list, However not all positions on the list are remote. I hope that will be okay.

**Comment by dougaitken** [comment]
That link isn't in the PR @LadySith, can you amend please? As long as the company hires some employees remotely, that is okay.

**Comment by LadySith** [comment]
@dougaitken added it now

**Pull request merged**
