### PR TITLE
Adds CartoDB

### PR DESCRIPTION
**Pull request by javierarce**
This PR adds `cartodb.com` to the list. An example of a remote job offer: https://cartodb.com/jobs/junior-designer.

### CODE REVIEW

**Comment by hkdobrev** [comment]
@javierarce I don't know about the remote culture in CartoDB, but the job offer you've linked mentions:

> This position is based in our Madrid office, although we often work remotely.
Which implies you need to be in Madrid and could sometimes not come to the office, which is not really the same as for example GitHub or Travis CI which have a large chunk of their employees across the globe.

**Comment by javierarce** [comment]
You are totally right, Haralan, but I guess it would be semi-remote friendly then :) We have several people working remotely full-time and others that come to the office (in Madrid or NY) whenever they want.

**Comment by jessicard** [comment]
Partially remote is OK! Thanks for checking. In the future, I should add a column for what kind of remote it is. Thanks :)

**Comment by hkdobrev** [comment]
@javierarce Thanks for the reply! :+1:

**Comment by javierarce** [comment]
Thanks to both of you! :)

**Pull request merged**
