### PR TITLE
Updated Doist site & location

### PR DESCRIPTION
**Pull request by hjotar**

### CODE REVIEW

**Comment by dougaitken** [comment]
Hey @hjotar, cheers for this! Can you add a company profile too?

**Comment by hjotar** [comment]
Sure, let me coordinate a few details with my peers :+1:

**Comment by dougaitken** [comment]
Brilliant, always looking for employee submitted PRs!

**Comment by hjotar** [comment]
@dougaitken done :)

**Comment by dougaitken** [comment]
Yoooo! Let's do this, great work @hjotar! :shipit:

**Pull request merged**
