### PR TITLE
Adding Crew.co

### PR DESCRIPTION
**Pull request by dougaitken**
Hey! 

Hopefully this works this time, I added Crew, if this looks okay, I've got 3 more to add, and I can probably help flesh out some of the examples

### CODE REVIEW

**Comment by jessicard** [comment]
Thanks! This looks great. Unfortunately I created a conflict for you but it should be really quick to resolve, i'm sorry about that. Do you mind resolving real fast so I can merge? Also, I'd love having you submit the other companies, that would be great.

**Comment by dougaitken** [comment]
hahah @jessicard, that's 2/2 for conflicts, go me! hah. 

I'll get that sorted now.

**Comment by jessicard** [comment]
@dougaitken The conflict was my bad :) Thanks for adding this 2nd profile! I don't see Crew in the list now - mind adding it and I'll merge this in?

**Comment by dougaitken** [comment]
Utter facepalm. I guess I deleted it when trying to sort the merge conflict. Should be all good now!

**Comment by jessicard** [comment]
Woohoo! :) Thank you so much!

**Comment by dougaitken** [comment]
hahah finally! You're welcome :+1:

**Pull request merged**
