### PR TITLE
Adding Formstack company profile.

### PR DESCRIPTION
**Pull request by czeeb**

### CODE REVIEW

**Comment by jessicard** [comment]
Awesome! Thanks for making this. It looks like I merged something that caused a conflict - mind resolving quickly? Thanks, and sorry about that!

**Comment by jessicard** [comment]
@czeeb Ping!

**Comment by czeeb** [comment]
@jessicard Sorry it took me so long to resolve that merge conflict.  Should be all good now!

I was too busy playing with this guy, I think you'll understand!  http://imgur.com/pR0q53P

**Comment by jessicard** [comment]
Oh my god @czeeb your pup 😍 Thanks for fixing!!

**Pull request merged**
