### PR TITLE
Remove "Wordpress" from company list

### PR DESCRIPTION
**Pull request by morganestes**
wordpress.com is run by Automattic (already on the list) and isn't a separate company.
WordPress, however, is fantastic software built buy hundreds of volunteers from around the world. :D

### CODE REVIEW

**Comment by jessicard** [comment]
Good call! Do you mind fixing the additional removals you have? I think you just need to pull. Thanks! :)

**Comment by jessicard** [comment]
Thanks @morganestes! :)

**Comment by morganestes** [comment]
Sorry about the screwy-ness of it. I used the GitHub editor for a one-off PR and that turned ugly real quick. Hope I didn't make too much of a mess for you.

**Comment by jessicard** [comment]
No mess at all! The repo is changing really fast, so a lot of people are experiencing conflicts. Thank you for your help! :)

**Pull request merged**
