### PR TITLE
Add simplabs

### PR DESCRIPTION
**Pull request by oliverbarnes**
Hello @jessicard, would you add us to the list please?

cheers
Oliver

### CODE REVIEW

**Comment by dougaitken** [comment]
@oliverbarnes Hey! Can you add a company profile and link from the readme entry and I'll merge when it's ready? thanks!

**Comment by oliverbarnes** [comment]
@dougaitken sure, added. @marcoow would you give it a quick look, please

**Comment by marcoow** [comment]
👍🏻 looks good

**Comment by oliverbarnes** [comment]
@dougaitken ready to merge. thanks!

**Comment by dougaitken** [comment]
cheers lads! @oliverbarnes @marcoow

**Pull request merged**
