### PR TITLE
Angular-backed interface

### PR DESCRIPTION
**Pull request by lbotinelly**
Tiny Angular application that parses the original README.md file and translates it into a searchable master list/detail structure.

2015-12-02 19_38_24-localhost_59274

Initial pull. Lots to fix, but functional.

Sample here: 

https://rawgit.com/lbotinelly/remote-jobs/master/index.html

### CODE REVIEW

**Comment by alephmelo** [comment]
This is awesome!! :+1:

**Comment by lbotinelly** [comment]
Functional global search:

2015-12-02 23_58_43-localhost_59274_index html

**Comment by dougaitken** [comment]
This is super cool, thanks @lbotinelly!

**Comment by lbotinelly** [comment]
Thank you, @alephmelo and @dougaitken!

**Comment by jessicard** [comment]
Wow, this is cool! Were you thinking this would work well for a github pages site?

**Comment by lbotinelly** [comment]
@jessicard ty! That's a possibility, since there's no backend processing whatsoever. Do you have anything in mind you'd like to see?

**Comment by dougaitken** [comment]
I kept thinking about this when you first posted the issue @jessicard

If you want to fling something on a gh-pages branch Lee then we can play
with it from there, sound like a plan Jessica?

**Comment by dougaitken** [comment]
@lbotinelly Do you want to create a gh-pages branch and we can look into this from there, separate from the main repo. It'll also allow us to use that if we choose to go in the web-app direction for visitors to use the data :+1:

**Comment by lbotinelly** [comment]
Sounds good! I'll give it a try this weekend (or earlier if possible).

**Comment by dougaitken** [comment]
No worries @lbotinelly. One thing I think would be good is when you click on a company further down the list, the readme still parses at the top of the page, it doesn't "float" down to where you have clicked. Just an idea :+1:

**Comment by dougaitken** [comment]
Hey @lbotinelly, are you still interested in doing something like this? I was thinking we could start a pages branch and go from there?

**Comment by dougaitken** [comment]
closing in favour of discussion in #44 if and when I decided to take that somewhere.

**Pull request closed without merging**
