### PR TITLE
feat: @AngularClass

### PR DESCRIPTION
**Pull request by gdi2290**

### CODE REVIEW

**Comment by jessicard** [comment]
Thanks @gdi2290! It looks like there are some conflicts, mind resolving? Also, do you mind quickly filling out the region information & a company profile?

**Comment by gdi2290** [comment]
oops, yeah

**Comment by jessicard** [comment]
Thanks! :)

**Comment by jessicard** [comment]
Fixed here: https://github.com/jessicard/remote-jobs/commit/6d89edf5b4c1216b97b6575bf635e302b1523d6e. Feel free to add region & company profile in a new PR!

**Comment by gdi2290** [comment]
thanks! I added the region via https://github.com/jessicard/remote-jobs/pull/109

**Pull request closed without merging**
