### PR TITLE
Add several companies

### PR DESCRIPTION
**Pull request by rubenlozano**
Add several companies to the list.

### CODE REVIEW

**Comment by dougaitken** [comment]
Are you able to add any company profiles for these please @rubenlozano

**Comment by rubenlozano** [comment]
Sure @dougaitken. I'll do it during next days.

**Comment by dougaitken** [comment]
Hi @rubenlozano any update on these? Please resolve the conflicts and then push to this PR & I'll merge when ready :+1:

**Comment by rubenlozano** [comment]
Hi @dougaitken. Give me a few days and I'll do it. I'm kind of busy with other things :)

**Comment by dougaitken** [comment]
Not a problem @rubenlozano, in your own time, it's an awesome list you've added anyway!

**Comment by rubenlozano** [comment]
Hi @dougaitken. I added several company profiles. I think you should push this PR :) If I find more free time I will include more profiles in the future.

**Comment by dougaitken** [comment]
Hey @rubenlozano, can you fix the merge conflicts please & I'll merge, thanks 👍🏻

**Comment by rubenlozano** [comment]
Done @dougaitken.

**Comment by dougaitken** [comment]
All aboard the merge train, cheers!

**Pull request merged**
